name: messenger_bottle
description: "A messenger bottle application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # 状态管理
  flutter_bloc: ^8.1.4
  provider: ^6.1.2
  
  # 路由管理
  go_router: ^13.2.0
  
  # 网络请求
  dio: ^5.4.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # 工具库
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # 3D渲染
  flutter_cube: ^0.1.1
  three_dart: ^0.0.16
  
  # 物理引擎
  flutter_physics: ^1.0.8
  
  # 数学计算
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # 代码生成
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  
  # 测试工具
  mockito: ^5.4.4
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/
